# Generated by Django 5.1.2 on 2024-10-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corporate_project_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="company",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="image",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="project",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="project",
            name="employee",
        ),
        migrations.RemoveField(
            model_name="project",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name="employee",
            name="gender",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="employee",
            name="phone_number",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="project",
            name="budget",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="project",
            name="duration",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(max_length=255),
        ),
    ]
