# Generated by Django 5.1.2 on 2024-10-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "corporate_project_app",
            "0002_remove_company_created_at_remove_company_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
